# Язык / Language: ru / en
language: 'ru'
default_group: 'default'

# Список игроков, которым разрешено иметь OP / List of players allowed to have OP
whitelist:
  - 'Zero3epo'
  - 'zozer22'
  - 'Ablar1m'
  - 'zo2zer22'
  - 'RayoHaruka'